---
sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
install: gem uninstall -ax bundler; gem install bundler -v 1.13.7; bundle install --jobs=3 --retry=3     
script:
- bundle exec rspec spec
jdk: oraclejdk8
before_install: []
