---
sudo: false
language: ruby
cache: bundler
rvm:
- jruby-1.7.25
install: yes | rvm @global do gem uninstall -ax bundler; rvm @global do gem install bundler -v '1.13.7'
script:
- bundle exec rspec spec
jdk: oraclejdk8
before_install: []
